In [1]:
from tensorflow.keras.preprocessing.text import one_hot


In [2]:
sent=[
    'The glass of milk',
    'The glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good'
]

In [3]:
sent


['The glass of milk',
 'The glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
voc_size=10000


In [5]:
one_hot_repr=[one_hot(words,voc_size) for words in sent]
one_hot_repr  

[[1383, 7952, 4468, 1127],
 [1383, 7952, 4468, 2328],
 [1383, 6272, 4468, 4264],
 [5190, 1183, 6539, 1092, 1926],
 [5190, 1183, 6539, 1092, 519],
 [2971, 1383, 5582, 4468, 5058],
 [1777, 3945, 6314, 1092]]

In [6]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
sent_len=8


In [9]:
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_len)
embedded_docs

array([[   0,    0,    0,    0, 1383, 7952, 4468, 1127],
       [   0,    0,    0,    0, 1383, 7952, 4468, 2328],
       [   0,    0,    0,    0, 1383, 6272, 4468, 4264],
       [   0,    0,    0, 5190, 1183, 6539, 1092, 1926],
       [   0,    0,    0, 5190, 1183, 6539, 1092,  519],
       [   0,    0,    0, 2971, 1383, 5582, 4468, 5058],
       [   0,    0,    0,    0, 1777, 3945, 6314, 1092]])

In [10]:
#dimentsion features
dim=10

In [11]:
model_ex=Sequential()
model_ex.add(Embedding(voc_size,dim,input_length=sent_len))
model_ex.compile('adam','mse')

In [12]:
model_ex.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [13]:
model_ex.predict(embedded_docs) #all sentance of var into 10 vector values for each word in sentance.

1/1 [==============================] - 0s 56ms/step


array([[[-2.05173846e-02, -2.41352078e-02,  1.28110908e-02,
         -4.48735617e-02,  4.27126773e-02,  2.57114805e-02,
          1.28206350e-02, -1.36888735e-02, -3.39353904e-02,
         -3.12067624e-02],
        [-2.05173846e-02, -2.41352078e-02,  1.28110908e-02,
         -4.48735617e-02,  4.27126773e-02,  2.57114805e-02,
          1.28206350e-02, -1.36888735e-02, -3.39353904e-02,
         -3.12067624e-02],
        [-2.05173846e-02, -2.41352078e-02,  1.28110908e-02,
         -4.48735617e-02,  4.27126773e-02,  2.57114805e-02,
          1.28206350e-02, -1.36888735e-02, -3.39353904e-02,
         -3.12067624e-02],
        [-2.05173846e-02, -2.41352078e-02,  1.28110908e-02,
         -4.48735617e-02,  4.27126773e-02,  2.57114805e-02,
          1.28206350e-02, -1.36888735e-02, -3.39353904e-02,
         -3.12067624e-02],
        [-3.84075567e-03, -6.46048784e-03, -8.99835676e-03,
         -2.91358717e-02,  9.83766466e-03, -4.29865234e-02,
          2.93354727e-02,  3.10312025e-02,  1.559890

In [14]:
model_ex.predict(embedded_docs[0]) #one sentance 8 words into each word 10 vectors so 80 vector for a single sentance

1/1 [==============================] - 0s 36ms/step


array([[-0.02051738, -0.02413521,  0.01281109, -0.04487356,  0.04271268,
         0.02571148,  0.01282063, -0.01368887, -0.03393539, -0.03120676],
       [-0.02051738, -0.02413521,  0.01281109, -0.04487356,  0.04271268,
         0.02571148,  0.01282063, -0.01368887, -0.03393539, -0.03120676],
       [-0.02051738, -0.02413521,  0.01281109, -0.04487356,  0.04271268,
         0.02571148,  0.01282063, -0.01368887, -0.03393539, -0.03120676],
       [-0.02051738, -0.02413521,  0.01281109, -0.04487356,  0.04271268,
         0.02571148,  0.01282063, -0.01368887, -0.03393539, -0.03120676],
       [-0.00384076, -0.00646049, -0.00899836, -0.02913587,  0.00983766,
        -0.04298652,  0.02933547,  0.0310312 ,  0.0155989 , -0.0113529 ],
       [-0.03738749,  0.02024534,  0.01908718, -0.01877507,  0.02945857,
        -0.00246442, -0.0201686 ,  0.02373595, -0.02133881, -0.01470431],
       [-0.04651977,  0.03824998,  0.01052332, -0.03201491, -0.02910061,
        -0.03108245, -0.01261835,  0.00312706